# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20160601_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 1, 22, 15, 16, 372278, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 1, 22, 15, 22, 932396, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contact', to='member.Member', verbose_name='member'),
        ),
    ]
