# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20160601_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 22, 16, 17, 4, 731683, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 16, 17, 10, 875922, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
